spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sports_tracker
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

balldontlie:
  api-key: ${BALLDONTLIE_API_KEY}